= Conceptos básicos de Java
:doctype: article
:encoding: utf-8
:lang: es
:toc: left
:toclevels: 3
:sectnums:

== Tipos primitivos
Los tipos primitivos son aquellos que solo guardan un tipo de dato simple y se almacenan directamente en la memoria.

[options="header", cols="3"]
|===
| Tipo
| Valor
| Tamaño (bits)

| boolean
| true, false
| 1

| char
| Carácter unicode
| 16

| byte
| Entero
| 8

| short
| Entero
| 16

| int
| Entero
| 32

| long
| Entero
| 64

| float
| Decimal
| 32

| double
| Decimal
| 64
|===

También existen clases complejas o _wrappers_ para algunos tipos primitivos:

- Boolean
- Character
- Integer
- Long
- Float
- Double

== Declaración de variables
Las variables pueden ser de cualquier tipo primitivo mencionado anteriormente, de sus clases complejas (wrappers), de clases propias de Java o de clases creadas por nosotros (objetos).

Por ejemplo:

- int n = 0;
- Integer n = 0;
- String frase = "Hello world!";
- Scanner scanner = new Scanner(System.in);
- Persona persona = new Persona(18, "John Doe");

En el caso de querer instanciar una variable cuyo valor no cambiará nunca, lo haremos con la palabra _final_. Además, es conveniente escribir el nombre de la variable en mayúsculas para diferenciarla mejor.

Por ejemplo:

- final int MAXIMO = 10;

== Operadores
Hay muchos tipos de operadores en Java y sirven para realizar cálculos y operaciones diversas.

=== Operadores aritméticos

[options="header", cols="4"]
|===
| Operador
| Descripción
| Ejemplo de uso
| Resultado

| +
| Suma
| 2 + 1
| 3

| -
| Resta
| 2 - 1
| 1

| *
| Producto
| 2 * 2
| 4

| /
| Divide
| 12 / 2
| 6

| %
| Residuo
| 12 % 2
| 0

| ++
| Incrementa el valor en uno
| 1++
| 2

| --
| Decrementa el valor en uno
| 2--
| 1
|===

=== Operadores de asignación

[options="header", cols="4"]
|===
| Operador
| Descripción
| Ejemplo de uso
| Resultado

| +=
| Suma combinada
| a += b
| a = a + b

| -=
| Resta combinada
| a -= b
| a = a - b

| *=
| Producto combinado
| a *= b
| a = a * b

| /=
| División combinada
| a /= b
| a = a / b

| %=
| Residuo combinado
| a %= b
| a = a % b
|===

=== Operadores de comparación

[options="header", cols="4"]
|===
| Operador
| Descripción
| Ejemplo de uso
| Resultado

| ==
| Igual que
| 7 == 8
| false

| !=
| Diferente que
| 7 != 8
| true

| <
| Menor que
| 11 < 19
| true

| >
| Mayor que
| 11 > 19
| false

| <=
| Menor o igual que
| 11 <= 19
| true

| >=
| Mayor o igual que
| 11 >= 19
| false
|===

=== Operadores lógicos

[options="header", cols="4"]
|===
| Operador
| Descripción
| Ejemplo de uso
| Resultado

| !
| Negación (NOT)
| !false
| true

| \|\|
| Suma lógica (OR)
| true \|\| false
| true

| &&
| Producto lógico (AND)
| false && true
| false
|===

=== Operadores de bits
[options="header", cols="4"]
|===
| Operador
| Descripción
| Ejemplo de uso
| Resultado

| ~
| Negación (NOT)
| ~2
| -3

| \|
| Suma lógica (OR)
| true \| false
| true

| &
| Producto lógico (AND)
| true & false
| false

| ^
| Suma lógica exclusiva (XOR)
| true ^ false
| true

| <<
| Desplazamiento a la izquierda
| 5 << 1
| 10

| >>
| Desplazamiento a la derecha
| 18 >> 1
| 9

| >>>
| Desplazamiento a la derecha sin signo
| -24 >>> 1
| 2147483636
|===

== Bifurcaciones
Las bifurcaciones se usan para ejecutar ciertas partes del código basandose en el resultado booleano de una comparación. Existen tres tipos.

=== If-else
La bifurcación if-else es la más común. Se usa una declaración _if_, se puede acompañar de tantas declaraciones _if else_ como sea necesario y se termina con una declaración _else_.

Ejemplo de uso:
[source, java]
----
int a = 4;
int b = 7;
int c = -2

if (a > b && a > c) {
    System.out.println(a + " es el mayor");
} else if (b > c) {
    System.out.println(b + " es el mayor");
} else {
    System.out.println(c + " es el mayor");
}
----

=== Switch-case
La bifurcación switch-case es muy parecida a la if-else pero puede resultar más útil en ciertos casos. De manera similar, se usa una declaración _switch_, se puede acompañar de tantas declaraciones _case_ como sea necesario, y se termina con una declaración _default_.

Ejemplo de uso:
[source, java]
----
int dia = 4;
switch (dia) {
    case 1:
        System.out.println("Lunes");
    break;
    case 2:
        System.out.println("Martes");
    break;
    case 3:
        System.out.println("Miércoles");
    break;
    case 4:
        System.out.println("Jueves");
    break;
    case 5:
        System.out.println("Viernes");
    break;
    case 6:
        System.out.println("Sábado");
    break;
    case 7:
        System.out.println("Domingo");
    break;
    default:
        System.out.println("No existe este dia de la semana");
}
----

=== Operador ternario
El operador ternario es una simplificación de la bifurcación if-else para poder escribir sentencias con dos casos posibles de forma rápida. Se usa una condición seguida de una interrogación (?) y luego dos valores separados por dos puntos (:). El primer valor será asignado en caso que la condición sea _true_ y el segundo valor será asignado en caso que la condición sea _false_.

Ejemplo de uso:
[source, java]
----
int n = 6;
int salida = (n % 2 == 0) ? n + " es par" : n + " es impar";
System.out.println(salida);
----

== Bucles
Los bucles se usan para poder ejecutar bloques de código repetidamente. Existen cuatro tipos.

=== For
El bucle for es el más común. Se usa para repetir un bloque de código un número de veces definido. En el caso del siguiente ejemplo, cada iteración del bucle ejecutará el bloque de código e incrementará la variable _i_. Esto sucederá hasta que _i_ sea menor que 10.

Ejemplo de uso:
[source, java]
----
for (int i = 0; i < 10; i++) {
    System.out.print(i + " ");
}
----

=== For-each
El bucle for-each es una variación del bucle for. Se introdujo porque son muchas las ocasiones en las que hay que recorrer arrays o listas. En el caso del siguiente ejemplo, cada iteración dará acceso a _n_. Esto sucederá hasta que se hayan recorrido todos los elementos del array.

Ejemplo de uso:
[source, java]
----
for (int n : numeros) {
    System.out.print(n + " ");
}
----

=== While
Al contrario que los dos anteriores, el bucle while no depende de un numero definido de iteraciones, sino que depende de que una condición se cumpla. Por ello, el único parámetro que recibe es una expresión booleana. En el caso del siguiente ejemplo, el bucle se ejecutará hasta que _salir_ sea true, es decir, hasta que el contador alcance un numero mayor que 10.

Ejemplo de uso:
[source, java]
----
boolean salir = false;
int contador = 0;
while (!salir) {
    if (contador > 10) {
        salir = true;
    } else {
        System.out.println(contador + " ");
    }
}
----

=== Do-while
El bucle do-while es una variación del bucle while. En el caso del anterior bucle, si la variable _salir_ es _true_ antes de ejecutar el bucle, el bloque de código dentro de este no se ejecutará, puesto que la condición de salida ya es cierta. Aquí es donde encontramos la utilidad del bucle do-while. Si necesitamos que el bloque de código dentro del bucle se ejecute mínimo una vez, usaremos este bucle. En el caso del siguiente ejemplo, aunque la condición ya se cumple, el bucle se ejecutará una vez.

Ejemplo de uso:
[source, java]
----
boolean salir = true;
int contador = 0;
do {
    if (contador > 10) {
        salir = true;
    } else {
        System.out.println(contador + " ");
    }
} while (!salir);
----

En el caso del siguiente ejemplo, la condición no se cumple de primeras, así que el bucle seguirá su curso como si se tratara de cualquier otro bucle.

Ejemplo de uso:
[source, java]
----
boolean salir = false;
int contador = 0;
do {
    if (contador > 10) {
        salir = true;
    } else {
        System.out.println(contador + " ");
    }
} while (!salir);
----

== String
La clase String pertenece a Java y *NO* es un tipo primitivo, al contrario del o que muchos piensan. Se podría comparar a un array de _char_. Esta clase siempre se construye usando comillas dobles (""). Para introducir ciertos carácteres hace falta escribirlos de una manera especial, son los denominados _carácteres de escape_.

[options="header", cols="2"]
|===
| Carácter de escape
| Valor

| \b
| Retroceso

| \t
| Tabulación

| \n
| Nueva línea

| \f
| Avance de línea

| \r
| Retorno

| \"
| Comillas dobles

| \'
| Comillas simples

| \\
| Contrabarra

| \uxxxx
| Carácter unicode correspondiente al valor de xxxx
|===

=== Métodos más comunes
Como todas las clases, la clase String viene con un montón de métodos que nos facilitan algunas tareas. Estos son algunos de los más comunes y útiles.

[options="header", cols="4"]
|===
| Método
| Descripción
| Ejemplo de uso
| Resultado

| charAt(int index)
| Devuelve el cáracter del String ubicado en el índice especificado
| "Ejemplo".charAt(3)
| 'm'

| compareTo(String anotherString)
| Compara dos Strings por carácteres (lexicográficamente)
| "Ejemplo".compareTo("Ejemplo")
| 0

| compareToIgnoreCase(String anotherString)
| Compara dos Strings por carácteres (lexicográficamente) ignorando las mayúsculas y minúsculas
| "Ejemplo".compareToIgnoreCase("ejemplo")
| 0

| contains(CharSequence s)
| Comprueba si el String contiene la secuencia especificada.
| "Ejemplo".contains("os")
| false

| endsWith(String suffix)
| Comprueba si el String termina con el sufijo especificado.
| "Ejemplo".endsWith("lo")
| true

| equals(Object object)
| Comprueba si el String es igual al objeto especificado (normalmente otro String)
| "Ejemplo".equals("ejemplo")
| false

| equalsIgnoreCase(String anotherString)
| Comprueba si el String es igual que otro String ignorando las mayúsculas y minúsculas
| "Ejemplo".equalsIgnoreCase("ejemplo")
| true

| indexOf(String str, int fromIndex)
| Devuelve el índice dentro del String de la primera coincidencia con el substring especificado. Si no se define fromIndex, este será el inicio del String.
| "Ejemplo".indexOf("mp")
| 3

| isBlank()
| Comprueba si el String está vacio o solo contiene espacios
| " ".isBlank()
| true

| isEmpty()
| Comprueba si el String tiene una longitud de 0
| " ".isEmpty()
| false

| lastIndexOf(String str, int fromIndex)
| Devuelve el índice dentro del String de la última coincidencia con el substring especificado. Si no se define fromIndex, este será el inicio del String.
| "Ejemplo".lastIndexOf("e")
| 2

| length()
| Devuelve la longitud del String
| "Ejemplo".length()
| 7

| repeat(int count)
| Devuelve un String con su valor concatenado el número de veces especificado
| "Ejemplo".repeat(3)
| "EjemploEjemploEjemplo" 

| replace(CharSequence target, CharSequence replacement)
| Reemplaza en el String cada substring que coincida con el especificado (target) por el reemplazo (replacement)
| "ejemplo".replace("e", "2")
| "2j2mplo"

| startsWith(String prefix)
| Comprueba si el String empieza con el prefijo especificado.
| "Ejemplo".startsWith("Ej")
| true

| substring(int beginIndex, int endIndex)
| Devuelve un String dentro del String entre el punto de inicio y final. Si no se define endIndex, este será el final de String.
| "Ejemplo".substring(2)
| "emplo"

| toCharArray()
| Convierte el String en un array de carácteres
| "Ejemplo".toCharArray()
| ['E', 'j', 'e', 'm', 'p', 'l', 'o']

| toLowerCase()
| Convierte el String a todo minúsculas
| "Ejemplo".toLowerCase()
| "ejemplo"

| toUpperCase()
| Convierte el String a todo mayúsculas
| "Ejemplo".toUpperCase()
| "EJEMPLO"

| trim()
| Devuelve el String eliminando los espacios del incio y del final
| "  Ejemplo ".trim()
| "Ejemplo"
|===

== Excepciones
Una excepción es la manera como Java nos avisa que ha habido un error durante la ejecución del programa, y se dividen en tres tipos distintos. Las excepciones _checked_ son comprobadas en tiempo de compilación y, por lo tanto, el compilador obliga a controlarlas con una cláusula _trhows_ o un bloque try-catch. Por el contrario, las excepciones _unchecked_ son las que no se comprueban en tiempo de compilación, por lo que no es obligatorio controlarlas. Por último, las excepciones _fatal_ son aquellas que causan que el programa se detenga completamente, sugiriendo que alguna parte del código es incorrecta y debe ser corregida de immediato. Estas son algunas de las excepciones más comunes.

[options="header", cols="3"]
|===
| Nombre
| Tipo
| Descripción

| ArithmeticException
| Unchecked
| Operación aritmética excepcional, por ejemplo división por cero.

| ClassCastException
| Unchecked
| Una conversión (cast) es inválida entre clases.

| ClassNotFoundException
| Checked
| El programa intenta cargar una clase por su nombre (String) pero no se encuentra dicho nombre.

| FileNotFoundException
| Checked
| Fallo al intentar abrir o leer un archivo del sistema.

| IllegalAccessException
| Checked
| Se intenta acceder o invocar un método pero el programa no tiene acceso a este.

| IllegalArgumentException
| Unchecked
| Un método recibe un argumento ilegal o inapropiado.

| IndexOutOfBoundsException
| Unchecked
| Se intenta acceder a un índice inválio dentro de un string o array.

| InterruptedIOException
| Checked
| Una operación de la clase IO de Java ha sido interrumpida por algún motivo.

| NoClassDefFoundError
| Fatal (Error)
| Una clase disponible en tiempo de compilación no se encuentra en tiempo de ejecución.

| NullPointerException
| Unchecked
| Se intenta acceder o invocar a un método en una referencia nula.

| OutOfMemoryError
| Fatal (Error)
| La máquina virtual de Java (JVM) se ha quedado sin memoria con la que trabajar.

| StackOverflowError
| Fatal (Error)
| La pila de llamadas es demasiado larga, típicamente en una método recursivo infinito.

| UnknownError
| Fatal (Error)
| Un error desconocido pero serio ha ocurrido en la máquina virtual de Java (JVM).
|===

=== Throws
La cláusula throws se utiliza en la declaración de un método para indicar que este puede lanzar una o más excepciones _checked_. De esta manera, la excepción(es) se propaga(n) al método que lo llama, y este es el que se encarga de manejarla(s). 

Ejemplo de uso:
[source, java]
----
public void readFile(String path) throws IOException {
    // Código para leer el archivo
}
----

Ejemplo de uso:
[source, java]
----
public void dataBaseOperation() throws SQLException, IOException {
    FileReader fr = new FileReader(ruta);
    // Código que puede lanzar ambas excepciones
}
----

=== Try-catch
El bloque try-catch se utiliza para manejar excepciones. El código que puede lanzar la excepción se coloca en el bloque _try_, y el manejo de la excepción en el bloque _catch_.

Ejemplo de uso:
[source, java]
----
try {
    int resultado = 10 / 0;
} catch (ArithmeticException e) {
    System.out.println("Error: División por cero");
}
----

El bloque _catch_ no se limita a una sola excepción, también puede contener múltiples.

Ejemplo de uso:
[source, java]
----
try {
    File file = new File("archivo.txt");
    FileReader fr = new FileReader(file);
} catch (FileNotFoundException e) {
    System.out.println("El archivo no existe");
} catch (IOException e) {
    System.out.println("Error de lectura");
}
----

Ejemplo de uso:
[source, java]
----
try {
    File file = new File("archivo.txt");
    FileReader fr = new FileReader(file);
} catch (FileNotFoundException | IOException e) {
    System.out.println("Error con el archivo");
}
----

Además, existe un tercer integrante en esta estructura, que es el _finally_. Este bloque se ejecuta ya sea que la excepción se lanze o no.

Ejemplo de uso:
[source, java]
----
try {
    int resultado = 10 / 0;
} catch (ArithmeticException e) {
    System.out.println("Error: División por cero");
} finally {
    System.out.println("Fin del programa")
}
----

Y ya como extra, en la version 7 de Java se integró una función llamada "try with resources", el cual es una variación de todo lo que hemos visto, pero que acepta parámetros al comienzo del bloque.

Ejemplo de uso:
[source, java]
----
try (FileReader fr = new FileReader("archivo.txt")) { // El recurso (FileReader) se cerrará automáticamente
    // Código para leer el archivo
} catch (IOException e) {
    System.out.println("Error: " + e.getMessage());
}
----

== Arrays
Los arrays almacenan múltiples valores del mismo tipo en una única variable. Su longitud es fija y se determina al instanciarlo. Cada valor recibe un índice (0-X) con el cual puede ser referenciado. En los ejemplos de se van a declarar e instanciar arrays de tipo entero (_int_), pero como se ha mencionado anteriormente, estos pueden ser de cualquier tipo primitivo, clase, objeto, etc.

Ejemplo de uso:
[source, java]
----
int[] numeros; // Declaración del array, todavía no se ha instanciado
numeros = new int[10] // Instanciación del array, en este caso 10 posiciones
----

Estas dos lineas pueden ser simplificadas en una sin ningun problema. De igual manera, podemos instanciar el array especificando directamente sus valores y no solo su longitud.

Ejemplo de uso:
[source, java]
----
int[] numeros = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
----

Hasta el momento solo hemos visto arrays unidimensionales, pero estos pueden contener tantas dimensiones como queramos. Hay que tener en cuenta que nuestro mundo tiene tres dimensiones, así que es raro encontrar casos que necesiten de arrays con más de tres dimensiones.

Ejemplo de uso:
[source, java]
----
int[][] numeros = new int[10][10] // Array de dos dimensiones con 10 valores en cada una
int[][][] numeros2 = new int[10][10][10] // Array de tres dimensiones con 10 valores en cada una
----

Para acabar, al igual que pasa con la clase String, podemos conocer su longitud usando _.length_. Además para acceder al valor de una de sus posiciones es tan fácil como escribir su índice. Es muy común recorrer todas las posiciones de un array con un bucle _for_ o _for-each_, tal y como se explica en el apartado de bucles.

Ejemplo de uso:
[source, java]
----
int[] numeros = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}
numeros.length // El array "numeros" tiene una longitud de 10
numeros[2] // La posición 2 del array "numeros" contiene el valor 3
----